# Dockerfile - Windows
# https://github.com/openresty/docker-openresty


ARG RESTY_IMAGE_BASE="openresty/openresty"
ARG RESTY_IMAGE_TAG="windows"



FROM "${RESTY_IMAGE_BASE}:${RESTY_IMAGE_TAG}"

LABEL vendor="openIMIS"\
      maintainer="Patrick Delcroix <patrick.delcroix@swisspth.ch>"\
	  org.openimis.fe.is-beta= \
      org.openimis.fe.is-production="" \
      org.openimis.fe.version="${OPENIMIS_VERSION}" 
#RUN mkdir C:\openresty\conf

COPY ./script/entrypoint.bat C:/openresty/
COPY ./conf/nginx.conf C:/openresty/conf/nginx.conf
COPY ./conf/openimis_win.conf C:/openresty/openIMIS.conf.default
COPY ./certs C:/certs
COPY lua C:/openresty/lua
WORKDIR C:/openresty
# nginx config is not overwritten as paths in the Windows distribution are already fine

ARG TZ=Europe/Brussels
ENV TZ=$TZ
ENV NEW_OPENIMIS_HOST = ""
ENV LEGACY_OPENIMIS_HOST = ""
RUN del /f /q C:\openresty\logs\* >NUL
ENTRYPOINT C:/openresty/entrypoint.bat

